### ISSUE TITLE
Compilation fails in VScode (MiKTEX)

### ISSUE THREAD

**Issue by abhishekk79** [chrisby/prometheusCV#1]
I get the following error and keeps coming no matter what i try:

C:\Users\kabhi\AppData\Local\Programs\MiKTeX\tex/latex/fontspec\fontspec.sty:45: Fatal Package fontspec Error: The fontspec package requires either XeTeX or
(fontspec)                      LuaTeX.
(fontspec)                      
(fontspec)                      You must change your typesetting engine to,
(fontspec)                      e.g., "xelatex" or "lualatex" instead of
(fontspec)                      "latex" or "pdflatex".

Type <return> to continue.
 ...                                              
                                                  
l.45 \msg_fatal:nn {fontspec} {cannot-use-pdftex}
                                                 

Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
Reverting Windows console CPs to (in,out) = (437,65001)
Latexmk: Getting log file 'main.log'
Latexmk: Examining 'main.fls'
Latexmk: Examining 'main.log'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'main.log' and/or above output for details

I built using latexmk(xetlatex) from side panel.. I dont know what i am doing wrong
[main.log](https://github.com/chrisby/prometheusCV/files/12363381/main.log)

Attaching main.log

**Comment by chrisby** [comment]
Hey, looks like you're using pdflatex to compile. I am not sure how to change the compiler on VSCode. I'd recommend using this overleaf template to edit: https://www.overleaf.com/latex/templates/prometheuscv/hhkdyvbtvhsq
